eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    port: 8900
spring:
    application:
        name: dock-service
    datasource:
        initialization-mode: always
        password: Pass2020!
        platform: postgres
        url: jdbc:postgresql://localhost:5432/dock
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
