server:
  port: 9090

spring:
  profiles:
    active: "dev"
  application:
    name: zuul-server
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 10000
    eager-load:
      enabled: true
  #Service will be mapped under the /api URI
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
      account-service:
          path: /account/**
          serviceId: account-service
      auth-service:
          path: /auth/**
          sensitive-headers: "Cookie,Set-Cookie   "
          serviceId: auth-service
          strip-prefix: false
      dock-service:
          path: /dock/**
          serviceId: dock-service
      travel-history-receiver-service:
          path: /travel-history-receiver/**
          serviceId: travel-history-receiver-service
      travel-history-service:
          path: /travel-history/**
          serviceId: travel-history-service
      travel-history-process-service:
          path: /travel-history-process/**
          serviceId: travel-history-process-service
      rental-service:
          path: /rental/**
          serviceId: rental-service
      bikemanagement-service:
          path: /bike-management/**
          serviceId: bike-management-service
      dummy-service:
          path: /dummy/**
          serviceId: dummy-service
      feedback-service:
          path: /feedback/**
          serviceId: feedback-service
      payment-calculator-service:
          path: /payment-calculator/**
          serviceId: payment-calculator-service
      payment-manager-service:
          path: /payment-manager/**
          serviceId: payment-manager-service
      payment-service:
          path: /payment/**
          serviceId: payment-service
      token-manager:
        path: /token/**
        serviceId: token-manager
      notification-service:
        path: /notification/**
        serviceId: notification-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true 
  instance:
    # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
    preferIpAddress: true
    # The hostname of the service, to register the pod and turn it easier for the gateway to find it
    hostname: zuul-server
---

spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
