server:
    port: 8762
spring:
    application:
        name: zuul-server

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
                        
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
        preferIpAddress: true
        # The hostname of the service, to register the pod and turn it easier for the gateway to find it
        hostname: zuul-server

zuul:
    ribbon:
        eager-load:
        enabled: true
    ignored-services: "*"
    routes:
        account-service:
            path: /account/**
            serviceId: account-service
        auth-service:
            path: /auth/**
            sensitive-headers: "Cookie,Set-Cookie   "
            serviceId: auth-service
            strip-prefix: false
        dock-service:
            path: /dock/**
            serviceId: dock-service
