server:
  port: 8400
spring:
  profiles:
    active: "dev"
  application:
    name: payment-service
  datasource:
    initialization-mode: always
    password: Pass2020!
    platform: postgres
    username: postgres
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  
  kafka:
    producer:
      group-id: payment
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  payment:
    producer: payment
    
auto:
  create:
    topics:
      enable: true
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: payment-service

---
spring:
  profiles: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
    producer:
      bootstrap-servers: localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment
  
  kafka:
    consumer:
      bootstrap-servers: kafka-0.kafka.kafka:9092
    producer:
      bootstrap-servers: kafka-0.kafka.kafka:9092
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
