server:
  port: 8800
spring:
  profiles:
    active: "dev"
  application:
    name: bike-management-service
  datasource:
    initialization-mode: always
    password: Pass2020!
    platform: postgres
    username: postgres
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: bike-management-service

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bike

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://postgres-bike:5432/bike

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

