version: '3.3'
services:
    postgres:
        container_name: dev-postgres
        environment:
            - POSTGRES_PASSWORD=Pass2020!
        volumes:
            - '/home/daniel/postgres-data/:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        image: postgres