server:
  port: 9600
spring:
  profiles:
    active: "dev"
  application:
    name: payment-validator-service

  kafka:
    producer:
      group-id: payment-validator
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  payment:
    producer: payment-event
    consumer: payment

auto:
  create:
    topics:
      enable: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: payment-validator-service


---
spring:
  profiles: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9094

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

---
spring:
  profiles: dev


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

  kafka:
    consumer:
      bootstrap-servers: localhost:9094
    producer:
      bootstrap-servers: localhost:9094

---
spring:
  profiles: prod

  kafka:
    consumer:
      bootstrap-servers: kafka-0.broker.kafka:9092
    producer:
      bootstrap-servers: kafka-0.broker.kafka:9092

eureka:
  instance:
  client:
    service-url:
      default-zone: http://eureka:8761/eureka
