kind: Service
apiVersion: v1
metadata:
  name: travel-history-receiver-service
  labels:
    run: travel-history-receiver-service
spec:
  selector:
    run: travel-history-receiver-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9300

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-history-receiver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: travel-history-receiver-service
  template:
    metadata:
      labels:
        run: travel-history-receiver-service
    spec:
      containers:
        - name: travel-history-receiver-service
          image: registry.gitlab.com/danielpinto8zz6/bikeshare/travel-history-receiver-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9300
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JVM_OPTS
              value: "-Xms1g -Xmx1g"
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
      imagePullSecrets:
        - name: gitlab-auth
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata: 
  name: travel-history-receiver-service 
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travel-history-receiver-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80