server:
  port: 9700
spring:
  profiles:
    active: "dev"
  application:
    name: token-manager

  redis:
    port: 6379
    password: admin

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: token-manager

---
spring:
  profiles: dev
  redis:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  redis:
    host: redis

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
