server:
  port: 9800
spring:
  profiles:
    active: "dev"
  application:
    name: notification-service
management:
  security:
    enabled: false
security:
  basic:
    enable: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: notification
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  notification:
    consumer: notification

auto:
  create:
    topics:
      enable: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: notification-service

---
spring:
  profiles: dev
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka-0.broker.kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
