apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: mongodb-namespace
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb          
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
            - secretRef:
                name: mongodb-secret
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  #namespace: mongodb-namespace
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb