server:
  port: 9100
spring:
  profiles:
    active: "dev"
  application:
    name: payment-process-service

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: payment-process
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    initialization-mode: always
    password: Pass2020!
    platform: postgres
    username: postgres

  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

topic:
  payment-request:
    consumer: payment-request
  payment-event:
    consumer: payment-event
  notification:
    producer: notification

auto:
  create:
    topics:
      enable: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: payment-process-service

---
spring:
  profiles: dev

  kafka:
    consumer:
      bootstrap-servers: localhost:9094
    producer:
      bootstrap-servers: localhost:9094

  datasource:
    url: jdbc:postgresql://localhost:5432/payment

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod

  kafka:
    consumer:
      bootstrap-servers: kafka-0.kafka.kafka:9092
    producer:
      bootstrap-servers: kafka-0.kafka.kafka:9092

  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
