server:
  port: 8500
spring:
  profiles:
    active: "dev"
  application:
    name: rental-service

  datasource:
    initialization-mode: always
    password: Pass2020!
    platform: postgres
    username: postgres
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  
  kafka:
    producer:
      group-id: dock-event
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  unlock-bike:
    producer: unlock-bike
    
auto:
  create:
    topics:
      enable: true
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: rental-service

---
spring:
  profiles: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rental
  
  kafka:
    producer:
      bootstrap-servers: localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:postgresql://postgres-rental:5432/rental
  
  kafka:
    producer:
      bootstrap-servers: kafka-0.kafka.kafka:9092
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
