kind: Service
apiVersion: v1
metadata:
  name: dock-management-service
  labels:
    app: dock-management-service
spec:
  selector:
    app: dock-management-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dock-management-service
  labels:
    app: dock-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dock-management-service
  template:
    metadata:
      labels:
        app: dock-management-service
    spec:
      containers:
        - name: dock-management-service
          image: registry.gitlab.com/danielpinto8zz6/bikeshare/dock-management-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8900
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              memory: "512Mi"
              cpu: "512m"
      imagePullSecrets: 
      - name: gitlab-auth 
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata: 
  name: dock-management-service
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dock-management-service
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 80