server:
  port: 9300
spring:
  profiles:
    active: "dev"
  application:
    name: travel-history-receiver-service
  kafka:
    producer:
      group-id: travel-event
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  instance:
    preferIpAddress: true
    hostname: travel-history-receiver-service
  client:
    registerWithEureka: true
    fetchRegistry: true

travel-event:
  producer: travel-event

auto:
  create:
    topics:
      enable: true

---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: kafka-0.kafka.kafka:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
