server:
  port: 8200
spring:
  profiles:
    active: "dev"
  application:
    name: auth-service
management:
  security:
    enabled: false
security:
  basic:
    enable: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: auth-service

feign:
  hystrix:
    enabled: true

---
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka



