server:
  port: 8761
spring:
  profiles:
    active: "dev"
  application:
    name: eureka

eureka:
  numberRegistrySyncRetries: 1
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: dev
eureka:
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: false

---
spring:
  profiles: prod
eureka:
  instance:
    hostname: "${HOSTNAME}"

    