kind: Service
apiVersion: v1
metadata:
  name: dummy-service
  labels:
    app: dummy-service
spec:
  selector:
    app: dummy-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  labels:
    app: dummy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
        - name: dummy-service
          image: dummy-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
#      imagePullSecrets: 
#      - name: gitlab-dummy
