server:
    port: 8500
spring:
    application:
        name: rent-service
    datasource:
        initialization-mode: always
        password: Pass2020!
        platform: postgres
        url: jdbc:postgresql://localhost:5432/rent
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

auto:
    create:
        topics:
            enable: true
eureka:
    instance:
        # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
        preferIpAddress: true
        # The hostname of the service, to register the pod and turn it easier for the gateway to find it
        # For deploying eureka clients in Kubernetes you need to set the hostname as the same name of the service
        hostname: rent-service
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            default-zone: http://localhost:8761/eureka

    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: 127.0.0.1:9092
            group-id: bike-availability
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: 127.0.0.1:9092
            group-id: group_id
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
topic:
    name:
        consumer: bike-availability
        producer: topico.comando.teste
