server:
  port: 8900
spring:
  profiles:
    active: "dev"
  application:
    name: dock-management-service

  datasource:
    initialization-mode: always
    password: Pass2020!
    platform: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: dock-management
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      group-id: dock-management
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  rental:
    consumer: rental
  dock-event:
    producer: dock-event
    consumer: dock-event

auto:
  create:
    topics:
      enable: true

eureka:
  instance:
    preferIpAddress: true
    hostname: dock-management-service
  client:
    registerWithEureka: true
    fetchRegistry: true

---
spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/dock

  kafka:
    consumer:
      bootstrap-servers: localhost:9094
    producer:
      bootstrap-servers: localhost:9094

eureka:
  instance:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://postgres-dock:5432/dock

  kafka:
    consumer:
      bootstrap-servers: kafka-0.broker.kafka:9092
    producer:
      bootstrap-servers: kafka-0.broker.kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

