server:
  port: 9200
spring:
  profiles:
    active: "dev"
  application:
    name: dummy-service

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: dummy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      group-id: dummy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  open-dock:
    consumer: open-dock
  dock-closed:
    producer: dock-closed

auto:
  create:
    topics:
      enable: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: dummy-service

---
spring:
  profiles: dev

  kafka:
    bootstrap-servers: localhost:9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: prod

  kafka:
    bootstrap-servers: kafka-0.kafka.kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
