apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
  PGADMIN_DEFAULT_PASSWORD: "Pass2020!"
  PGADMIN_PORT: "80"
  PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
