apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
  labels:                                        # Labels applied to this deployment 
    app: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  serviceName: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pgadmin-secret
          ports:
            - containerPort: 80
              name: pgadminport
          volumeMounts:
            - mountPath: /data/pgadmin
              name: pgadmin-volume
  volumeClaimTemplates:
  - metadata:
      name: pgadmin-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: default
spec:
  ports:
  - name: padmin-port
    nodePort: 31560
    port: 80
    targetPort: 80
  selector:
    app: pgadmin
  type: LoadBalancer
