apiVersion: v1
kind: PersistentVolume                        # Create a PV
metadata:
  name: postgres-feedback-pv
  labels:
    name: postgres-feedback-pv
spec:
  storageClassName: postgres-feedback-sc                    # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-postgres-feedback
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain       # Retain the PV even after PVC is deleted. 

---
apiVersion: v1
kind: PersistentVolumeClaim                   # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                                     # Claim name and labels
  name: postgres-feedback-pvc
  labels:
    name: postgres-feedback-pvc
spec:                                         # Access mode and resource limits
  storageClassName: postgres-feedback-sc                     # Request a certain storage class
  accessModes:
    - ReadWriteOnce                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 10Gi
