kind: Service
apiVersion: v1
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  selector:
    app: zuul-server
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-server
  template:
    metadata:
      labels:
        app: zuul-server
    spec:
      containers:
        - name: zuul-server
          image: registry.gitlab.com/danielpinto8zz6/bikeshare/zuul-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

      imagePullSecrets: 
      - name: gitlab-auth
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata: 
  name: zuul-server
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zuul-server
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80