kind: Service
apiVersion: v1
metadata:
  name: dummy-service
  labels:
    app: dummy-service
spec:
  selector:
    app: dummy-service
  type: LoadBalancer
  ports:
    - name: padmin-port
      nodePort: 31600
      port: 80
      targetPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  labels:
    app: dummy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
        - name: dummy-service
          image: registry.gitlab.com/danielpinto8zz6/bikeshare/dummy-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              memory: "256Mi"

      imagePullSecrets: 
      - name: gitlab-auth
---

kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta2
metadata: 
  name: dummy-service
spec: 
  maxReplicas: 3 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummy-service
  metrics: 
  - type: Resource 
    resource: 
      name: memory 
      target:
        type: Utilization
        averageUtilization: 80
