apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-travel-history-pv-volume
  labels:
    type: local
    app: mongodb-travel-history
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mongodb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-travel-history-pv-claim
  labels:
    app: mongodb-travel-history
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
