apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:                                        # Labels applied to this deployment 
    app: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret" 
            - secretRef:
                name: postgres-account-secret
          ports:
            - containerPort: 80
              name: pgadminport
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
   - port: 80
     nodePort: 30200
