kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8200"
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: registry.gitlab.com/danielpinto8zz6/bikeshare/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets: 
      - name: gitlab-auth
